//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Agents
    {
              [System.ComponentModel.DataAnnotations.Key]
                [System.ComponentModel.DataAnnotations.Schema.Column(Order = 0)]
        public int AgentID { get; set; }
        public string AgentName { get; set; }
        public string Tel { get; set; }
        public string Remark { get; set; }
        public string Password { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Status { get; set; }
        public string LoginName { get; set; }
    }
}
