//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AirportDetails
    {
              [System.ComponentModel.DataAnnotations.Key]
                [System.ComponentModel.DataAnnotations.Schema.Column(Order = 0)]
        public string BillID { get; set; }
        public string PickUpFlightNo { get; set; }
        public Nullable<System.DateTime> PickUpDate { get; set; }
        public Nullable<int> PickUpDriverID { get; set; }
        public Nullable<double> PickUpFee { get; set; }
        public Nullable<int> PickUpMoneyID { get; set; }
        public Nullable<double> PickUpRealTimeFee { get; set; }
        public string SendFlightNo { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<int> SendDriverID { get; set; }
        public Nullable<double> SendFee { get; set; }
        public Nullable<int> SendMoneyID { get; set; }
        public Nullable<double> SendRealTimeFee { get; set; }
        public Nullable<int> VIPServerID { get; set; }
        public Nullable<int> VIPMoneyID { get; set; }
        public Nullable<double> VIPFee { get; set; }
        public Nullable<double> VIPRealTimeFee { get; set; }
        public Nullable<double> RealTimeFee { get; set; }
    }
}
