//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Bills
    {
              [System.ComponentModel.DataAnnotations.Key]
                [System.ComponentModel.DataAnnotations.Schema.Column(Order = 0)]
        public string BillID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ContactName { get; set; }
        public string Tel { get; set; }
        public string WeChat { get; set; }
        public string Address { get; set; }
        public Nullable<int> AdultCount { get; set; }
        public Nullable<int> ChildCount { get; set; }
        public Nullable<int> MoneyID { get; set; }
        public string HasPaid { get; set; }
        public Nullable<int> BusinessRecordID { get; set; }
        public Nullable<System.DateTime> BusinessDate { get; set; }
        public Nullable<int> DispatchRecordID { get; set; }
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string Remark { get; set; }
        public Nullable<double> RealTimeFee { get; set; }
    }
}
