//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Guides
    {
              [System.ComponentModel.DataAnnotations.Key]
                [System.ComponentModel.DataAnnotations.Schema.Column(Order = 0)]
        public int GuideID { get; set; }
        public string GuideName { get; set; }
        public string Tel { get; set; }
        public Nullable<double> LandFee { get; set; }
        public string Remark { get; set; }
        public Nullable<double> SeaFee { get; set; }
        public Nullable<double> AgentLandFee { get; set; }
        public Nullable<double> AgentSeaFee { get; set; }
        public string Contact { get; set; }
    }
}
