//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Schedule
    {
              [System.ComponentModel.DataAnnotations.Key]
                [System.ComponentModel.DataAnnotations.Schema.Column(Order = 0)]
        public int ScheduleID { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string Remark { get; set; }
        public Nullable<double> Fee { get; set; }
        public string Status { get; set; }
        public Nullable<int> Days { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string CustomRequire { get; set; }
        public Nullable<int> CustomerCount { get; set; }
    }
}
